baseurl = "http://izhengyin.com/"
languageCode = "zh-cn"
title = "izhengyin.com 分享使人愉悦"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "郑印"
	description = "85后程序员,专注Web应用开发."
	copyright = "Released under the MIT license"

	# Repository
	#provider = "GitHub"
	#repo_url = "https://github.com/zhengyin"

	version = ""
	logo = "images/logo.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "zhengyin"


[[menu.main]]
	name   = "文章索引"
	url    = "/post/category/"
	weight = 0



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true